services:
  db:
    image: pgvector/pgvector:0.7.4-pg15
    volumes:
      - helperai_pgdata:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helperai_development

  redis:
    image: redis:7.0.12
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6382:6379
    volumes:
      - helperai_redisdata:/data

  serverless-redis-http:
    ports:
      - "8089:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: "redis://redis:6379"
    depends_on:
      - redis

  nginx:
    image: nginx:1.27.2
    volumes:
      - ./local-nginx/helperai_dev.conf:/etc/nginx/conf.d/default.conf
      - ./local-nginx/certs:/etc/ssl/certs/
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"

  minio:
    image: minio/minio
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    volumes:
      - helperai_miniodata:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      if ! /usr/bin/mc ls myminio/helperai-private-storage-dev; then
        echo 'Bucket helperai-private-storage-dev does not exist. Creating...'
        /usr/bin/mc mb myminio/helperai-private-storage-dev;
      else
        echo 'Bucket helperai-private-storage-dev already exists.';
      fi;
      exit 0;
      "

volumes:
  helperai_pgdata:
  helperai_redisdata:
  helperai_miniodata:
