services:
  nginx:
    image: nginx:1.27.2
    volumes:
      - ./local-nginx/helperai_dev.conf:/etc/nginx/conf.d/default.conf
      - ./local-nginx/certs:/etc/ssl/certs/
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  helperai_pgdata:
