CREATE TABLE "issue_topics" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "issue_topics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"summary" text NOT NULL,
	"embedding" vector(1536)
);
--> statement-breakpoint
ALTER TABLE "conversations_conversation" ADD COLUMN "issue_topic_id" bigint;--> statement-breakpoint
CREATE INDEX "issue_topics_embedding_vector_idx" ON "issue_topics" USING hnsw ("embedding" vector_cosine_ops);--> statement-breakpoint
CREATE INDEX "conversations_issue_topic_id_idx" ON "conversations_conversation" USING btree ("issue_topic_id");