CREATE TABLE "macros_macro" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "macros_macro_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" varchar(50) NOT NULL,
	"name" varchar(100) NOT NULL,
	"content" text NOT NULL,
	"description" varchar(500),
	"mailbox_id" bigint NOT NULL,
	"created_by_user_id" text,
	"is_global" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"shortcut" varchar(20),
	"usage_count" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "macros_macro" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "macros_macro_mailbox_id_idx" ON "macros_macro" USING btree ("mailbox_id");--> statement-breakpoint
CREATE INDEX "macros_macro_created_by_user_idx" ON "macros_macro" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "macros_macro_slug_idx" ON "macros_macro" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "macros_macro_is_global_idx" ON "macros_macro" USING btree ("is_global");--> statement-breakpoint
CREATE INDEX "macros_macro_shortcut_idx" ON "macros_macro" USING btree ("shortcut");--> statement-breakpoint
CREATE UNIQUE INDEX "macros_macro_mailbox_shortcut_unique" ON "macros_macro" USING btree ("mailbox_id","shortcut") WHERE shortcut IS NOT NULL;