CREATE TABLE "recent_searches" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "recent_searches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"mailbox_id" bigint NOT NULL,
	"search_term" text NOT NULL,
	"last_used_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "recent_searches" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "recent_searches_user_id_idx" ON "recent_searches" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "recent_searches_mailbox_id_idx" ON "recent_searches" USING btree ("mailbox_id");--> statement-breakpoint
CREATE INDEX "recent_searches_user_mailbox_idx" ON "recent_searches" USING btree ("user_id","mailbox_id");--> statement-breakpoint
CREATE INDEX "recent_searches_last_used_at_idx" ON "recent_searches" USING btree ("last_used_at" DESC NULLS LAST);