CREATE TABLE "saved_replies" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "saved_replies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" varchar(50) NOT NULL,
	"name" varchar(100) NOT NULL,
	"content" text NOT NULL,
	"description" varchar(500),
	"mailbox_id" bigint NOT NULL,
	"created_by_user_id" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"shortcut" varchar(20),
	"usage_count" integer DEFAULT 0 NOT NULL
);

ALTER TABLE "saved_replies" ENABLE ROW LEVEL SECURITY;
CREATE INDEX "saved_replies_mailbox_id_idx" ON "saved_replies" USING btree ("mailbox_id");
CREATE INDEX "saved_replies_created_by_user_idx" ON "saved_replies" USING btree ("created_by_user_id");
CREATE INDEX "saved_replies_slug_idx" ON "saved_replies" USING btree ("slug");
CREATE INDEX "saved_replies_shortcut_idx" ON "saved_replies" USING btree ("shortcut");
CREATE UNIQUE INDEX "saved_replies_mailbox_shortcut_unique" ON "saved_replies" USING btree ("mailbox_id","shortcut") WHERE shortcut IS NOT NULL;