CREATE TABLE "cached_client_tools" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cached_client_tools_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"customer_email" text,
	"platform_customer_id" bigint,
	"tools" jsonb NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cached_client_tools" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "cached_client_tools_customer_idx" ON "cached_client_tools" USING btree ("customer_email");--> statement-breakpoint
CREATE INDEX "cached_client_tools_platform_customer_idx" ON "cached_client_tools" USING btree ("platform_customer_id");