CREATE TABLE "client_tools_cache" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_tools_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"mailbox_id" bigint NOT NULL,
	"tool_name" text NOT NULL,
	"description" text NOT NULL,
	"parameters" jsonb NOT NULL,
	"server_request_url" text NOT NULL,
	"customer_email" text,
	"platform_customer_id" text
);
--> statement-breakpoint
ALTER TABLE "client_tools_cache" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "client_tools_cache_mailbox_id_idx" ON "client_tools_cache" USING btree ("mailbox_id");--> statement-breakpoint
CREATE INDEX "client_tools_cache_customer_email_idx" ON "client_tools_cache" USING btree ("customer_email");--> statement-breakpoint
CREATE INDEX "client_tools_cache_platform_customer_id_idx" ON "client_tools_cache" USING btree ("platform_customer_id");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_client_tool_mailbox_customer_idx" ON "client_tools_cache" USING btree ("mailbox_id","tool_name","customer_email","platform_customer_id");