CREATE TABLE "customer_notes" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customer_notes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"body" text NOT NULL,
	"clerk_user_id" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "customer_notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "customer_notes_email_idx" ON "customer_notes" USING btree ("email");--> statement-breakpoint
CREATE INDEX "customer_notes_created_at_idx" ON "customer_notes" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "customer_notes_user_id_idx" ON "customer_notes" USING btree ("clerk_user_id");