ALTER TABLE conversations_conversation DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS conversations_conversation_mailbox_id_7fb25662;
ALTER TABLE conversations_conversation DROP CONSTRAINT IF EXISTS conversations_conversation_unused_mailboxId_fkey;
ALTER TABLE agent_threads DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS agent_threads_mailbox_id_idx;
ALTER TABLE agent_threads DROP CONSTRAINT IF EXISTS agent_threads_unused_mailboxId_fkey;
ALTER TABLE mailboxes_aiusageevent DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS mailboxes_aiusageevent_mailbox_id_a4908f79;
ALTER TABLE mailboxes_aiusageevent DROP CONSTRAINT IF EXISTS mailboxes_aiusageevent_unused_mailboxId_fkey;
ALTER TABLE faqs DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS faqs_mailbox_id_idx;
ALTER TABLE faqs DROP CONSTRAINT IF EXISTS faqs_unused_mailboxId_fkey;
ALTER TABLE guide_sessions DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS guide_sessions_mailbox_id_idx;
ALTER TABLE guide_sessions DROP CONSTRAINT IF EXISTS guide_sessions_unused_mailboxId_fkey;
ALTER TABLE guide_session_events DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS guide_session_events_mailbox_id_idx;
ALTER TABLE guide_session_events DROP CONSTRAINT IF EXISTS guide_session_events_unused_mailboxId_fkey;
ALTER TABLE guide_session_replays DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS guide_session_replays_mailbox_id_idx;
ALTER TABLE guide_session_replays DROP CONSTRAINT IF EXISTS guide_session_replays_unused_mailboxId_fkey;
ALTER TABLE mailboxes_metadataapi DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS mailboxes_metadataapi_mailbox_id_key;
ALTER TABLE mailboxes_metadataapi DROP CONSTRAINT IF EXISTS mailboxes_metadataapi_unused_mailboxId_fkey;
ALTER TABLE mailboxes_platformcustomer DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS mailboxes_platformcustomer_mailbox_id_58ea76bf;
ALTER TABLE mailboxes_platformcustomer DROP CONSTRAINT IF EXISTS mailboxes_platformcustomer_unused_mailboxId_fkey;
ALTER TABLE saved_replies DROP CONSTRAINT IF EXISTS saved_replies_unused_mailboxId_fkey;
ALTER TABLE saved_replies DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS saved_replies_mailbox_id_idx;
DROP INDEX IF EXISTS saved_replies_slug_mailbox_unique;
ALTER TABLE tool_apis DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS tool_apis_mailbox_id_idx;
ALTER TABLE tool_apis DROP CONSTRAINT IF EXISTS tool_apis_unused_mailboxId_fkey;
ALTER TABLE tools DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS tools_mailbox_id_idx;
ALTER TABLE tools DROP CONSTRAINT IF EXISTS tools_unused_mailboxId_fkey;
ALTER TABLE website_docs DROP COLUMN "unused_mailboxId";
DROP INDEX IF EXISTS website_docs_mailbox_id_idx;
ALTER TABLE website_docs DROP CONSTRAINT IF EXISTS website_docs_unused_mailboxId_fkey;
