-- Custom SQL migration file, put your code below! --

-- Create agent_threads table
CREATE TABLE IF NOT EXISTS "agent_threads" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  "mailbox_id" bigint NOT NULL,
  "slack_channel" text NOT NULL,
  "thread_ts" text NOT NULL
);

-- Create agent_messages table
CREATE TABLE IF NOT EXISTS "agent_messages" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  "agent_thread_id" bigint NOT NULL,
  "role" text NOT NULL,
  "content" text NOT NULL,
  "tool_name" text,
  "metadata" jsonb
);

-- Create indexes
CREATE INDEX "agent_threads_mailbox_id_idx" ON "agent_threads" ("mailbox_id");
CREATE INDEX "agent_threads_slack_channel_thread_ts_idx" ON "agent_threads" ("slack_channel", "thread_ts");
CREATE INDEX "agent_messages_agent_thread_id_idx" ON "agent_messages" ("agent_thread_id");
CREATE INDEX "agent_messages_role_idx" ON "agent_messages" ("role");

-- Add foreign key constraints
ALTER TABLE "agent_threads" ADD CONSTRAINT "agent_threads_mailbox_id_fkey" 
  FOREIGN KEY ("mailbox_id") REFERENCES "mailboxes_mailbox" ("id") ON DELETE CASCADE;

ALTER TABLE "agent_messages" ADD CONSTRAINT "agent_messages_agent_thread_id_fkey" 
  FOREIGN KEY ("agent_thread_id") REFERENCES "agent_threads" ("id") ON DELETE CASCADE;
