CREATE TABLE "agent_messages_message" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_messages_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"agent_thread_id" bigint NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"tool_name" text,
	"metadata" jsonb
);
--> statement-breakpoint
CREATE TABLE "agent_threads_thread" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_threads_thread_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"mailbox_id" bigint NOT NULL,
	"slack_channel" text NOT NULL,
	"thread_ts" text NOT NULL
);
--> statement-breakpoint
CREATE INDEX "agent_messages_agent_thread_id_idx" ON "agent_messages_message" USING btree ("agent_thread_id");--> statement-breakpoint
CREATE INDEX "agent_messages_role_idx" ON "agent_messages_message" USING btree ("role");--> statement-breakpoint
CREATE INDEX "agent_threads_mailbox_id_idx" ON "agent_threads_thread" USING btree ("mailbox_id");--> statement-breakpoint
CREATE INDEX "agent_threads_slack_channel_thread_ts_idx" ON "agent_threads_thread" USING btree ("slack_channel","thread_ts");--> statement-breakpoint

ALTER TABLE "agent_threads_thread" ADD CONSTRAINT "agent_threads_mailbox_id_fkey" 
  FOREIGN KEY ("mailbox_id") REFERENCES "mailboxes_mailbox" ("id") ON DELETE CASCADE;--> statement-breakpoint

ALTER TABLE "agent_messages_message" ADD CONSTRAINT "agent_messages_agent_thread_id_fkey" 
  FOREIGN KEY ("agent_thread_id") REFERENCES "agent_threads_thread" ("id") ON DELETE CASCADE;
